### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte

### ISSUE THREAD

**Issue by vladris** [vladris/tinkerer#1]
Copy/paste from bitbucket issue tracker:

Christian Jann created an issue 2012-08-05
[chris@thinkpad tinkerer.git]$ tinker -p "test: äüöß"
Traceback (most recent call last):
  File "/usr/bin/tinker", line 9, in <module>
    load_entry_point('Tinkerer==0.4b', 'console_scripts', 'tinker')()
  File "/usr/lib/python2.7/site-packages/Tinkerer-0.4b-py2.7.egg/tinkerer/cmdline.py", line 172, in main
    create_post(command.post[0], command.quiet, command.filename)
  File "/usr/lib/python2.7/site-packages/Tinkerer-0.4b-py2.7.egg/tinkerer/cmdline.py", line 75, in create_post
    new_post = post.create(title)
  File "/usr/lib/python2.7/site-packages/Tinkerer-0.4b-py2.7.egg/tinkerer/post.py", line 74, in create
    post.write()
  File "/usr/lib/python2.7/site-packages/Tinkerer-0.4b-py2.7.egg/tinkerer/post.py", line 65, in write
    "tags"      : tags})
  File "/usr/lib/python2.7/site-packages/Tinkerer-0.4b-py2.7.egg/tinkerer/writer.py", line 25, in render
    dest.write(env.get_template(template).render(context).encode("utf8"))
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 894, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/Tinkerer-0.4b-py2.7.egg/tinkerer/__templates/post.rst", line 1, in top-level template code
    {{ title }}
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 6: ordinal not in range(128)
ÄÜÖäüöß are frequently used German letters, they should work.

Comments (5)
Vlad Riscutia
edited description
assigned issue to   Vlad Riscutia
2012-08-05
Atamert Ölçgen
I can confirm this issue.
Workaround is to manually edit the heading inside the file, since these chars are not slug friendly anyway.

Mark as spam  Delete  2012-10-14
Christian Jann
I've added a fix here: https://bitbucket.org/christianjann/tinkerer/commits/5f29318e338f4d5d88d89da28d1c9d6b7b80c9fa.
A solution that will also work with python 3:

import sys

elif command.post:
-   if sys.version_info < (3,):
-       command.post[0] = command.post[0].decode(sys.stdin.encoding) #.decode('utf8')
  create_post(command.post[0], post_date, command.quiet, command.filename)
  Mark as spam  Delete  2013-02-02
  micolous
  Another way to handle the slugs is to pipe them through the translit module:
  http://pypi.python.org/pypi/translit/0.2a1

This way you can automatically make ASCII-only slugs for filenames.

Mark as spam  Delete  2013-02-04
Vlad Riscutia
Thanks! translit looks great, though this is Python3 only. I can probably merge the two fixes so it works on both version. I'll give it a shot after the next release.

**Comment by martin-ueding** [comment]
It would be nice to see this. I blog in German using Tinkerer and I currently resort to manually editing the title after escaping all the umlauts manually with “ä” to “ae” and so on.
